import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import Styles from './character.module.scss';

const defaultEndpoint = "https://rickandmortyapi.com/api/character";

export async function getServerSideProps({ query }) {
  const { id } = query;
  const resp = await fetch(`${defaultEndpoint}/${id}`);
  const data = await resp.json();
  return {
    props: {
      data
    }
  }
}

export default function Character({ data }) {
  const {name, image, episode, gender, location, species, status } = data;
  // location.name episodes.length
  return (
    <div>
      <Head>
        <title>{`${name}'s page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${Styles.character} txt_white`}>
        <h1 className={`${Styles.character_name} txt_21`}>{name}</h1>

        <Image layout='responsive' height={`300`} width={`300`}
        objectFit='cover' className={`${Styles.character_img}`}
        src={ image } alt={`${ name }'s closeup`} 
        />

        <section className={`${Styles.character_details} txt_16`}>
          <p  className={`${Styles.character_detail}`}>
            <span className={`${Styles.character_detail__span}`}>
            Gender: </span>
            { gender }
          </p>

          <p  className={`${Styles.character_detail}`}>
            <span className={`${Styles.character_detail__span}`}>
            Status: </span>
            { status }
          </p>

          <p  className={`${Styles.character_detail}`}>
            <span className={`${Styles.character_detail__span}`}>
            Location: </span>
            { location.name }
          </p>

          <p  className={`${Styles.character_detail}`}>
            <span className={`${Styles.character_detail__span}`}>
            Species: </span>
            { species }
          </p>

          <p className={`${Styles.character_detail} ${Styles.center}`}>
            Appears in { episode.length } episodes
          </p>
        </section>

        <div className={`${Styles.character_buttons} txt_white txt_16`}>
          <Link href="/"><a>
            Back to Search
          </a></Link>
        </div>
      </main>
    </div>
  )
}

// className={styles.container}